from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from .Functions.learning import learningSkill,learningKnowledge
# Create your views here.
def index(request):
    
    return render(request,"index.html");


def inputSkill(request):
    return render(request, "inputSkill.html")
    

def showSkills(request):
    Knowledges=learningSkill(request.GET["skill"]);
    return render(request,'listSkills.html',{'content': Knowledges })

def taskForSkill(request):
    print(request.POST.getlist('skills'))
    if request.method == 'POST':
        # Obtén los valores seleccionados de los checkboxes
        opciones_seleccionadas = request.POST.getlist('skills')
        save_learning_content = learningKnowledge(opciones_seleccionadas)
        return HttpResponse(f"<h1>The skills generated by AI are stored to path: {save_learning_content}</h1>")
        
        # Haz algo con las opciones seleccionadas
        
